---
- name: Clone arc-icon-theme repository
  git:
   repo=https://github.com/horst3180/arc-icon-theme.git
   dest={{ arc_icon_theme_install_path }}
  become: yes

- name: Create symlink
  file: src={{ arc_icon_theme_install_path }}/Arc dest=/usr/share/icons/Arc state=link
  become: yes
